### ISSUE TITLE
Different intervals for commit and push 

### ISSUE THREAD

**Issue by izzues** [denolehov/obsidian-git#106]
Thanks for the great work!

I'd like changes to be autocommited and autopushed, but I'd like the pushes to be less frequent than the commits. A new input could be added for this. What do you think?

**Comment by Vinzent03** [comment]
Could you explain your use case a bit more? Why don't always push?

**Comment by dbowling** [comment]
I'm not the OP on this, but I went looking for this setting because I am prompted for a password to my SSH key when a push happens. I'd like to do a commit every 5 minutes or so after a change, but only push once a day to limit those prompts.

I see a big difference between the disaster recovery benefit (pushing) and the benefit of point in time recovery (committing) for changes, or an "oops" event.
