### ISSUE TITLE
[Bug]: No action or keybinding to push

### ISSUE THREAD

**Issue by ohare93** [denolehov/obsidian-git#122]
### Describe the bug

I would like to push up to the remote when I am done. I do not want to use the automated push. I want to do it all from Obsidian, and not switch to the command line. There is an action and an associated keybinding for Pull, but not one for push.

Though in the ReadMe of this project is says this under features:

> Assign hotkeys for pulling/pushing changes to a remote repository

Yet I cannot do that.

### Steps to reproduce

-

### Expected Behavior

I push action and relevant hotkey that I can set. And/or that one can click on the Git message at the bottom right and select push as an option.

Just the ability to push when I want, really.

### Operating system

Windows

**Comment by Vinzent03** [comment]
There is a command called "Create backup", which commits and pushes the changes. Did you not know or do you really want a command to only push?

**Comment by ohare93** [comment]
I did not know this. That is a very confusing name for those who are used to using Git (two of us could not work this out for the life of us). I guess it is more suited to non-programers. Though I can not see that this is documented anywhere what that command does.

**Comment by soggylithe** [comment]
I was also confused because the naming seems to have changed since I was last using Obsidian between my two machines. My old workflow was just to open up the command panel and type "push" since it is a unique word in vanilla installs.

My original assumption was that this was a command for starting a new repo but looking through all commands I saw the one for Initializing, hence the confusion.

Changing the text of the command could be more descriptive of what is happening as well as giving more keywords to work with.

Plus is there a reason not to have the option for commit only or push only? It could be useful to people in some instances and doesn't conflict with the current commands. There is even support for doing this already it just requires moving off the keyboard and clicking the buttons in source control view.

Cheers and thanks for all the activity on this awesome plugin.
