### ISSUE TITLE
[Bug]: Authentication failed. Please try with different credentials.

### ISSUE THREAD

**Issue by quacau** [denolehov/obsidian-git#336]
I use Obsidian Git on my phone and I cannot push the data. It still pulls just fine. It keeps saying 

> Authentication failed. Please try with different credentials.

Do you have any idea?

Here is my config file:
```
[core]
    repositoryformatversion = 0
    filemode = false
    bare = false
    logallrefupdates = true
    symlinks = false
    ignorecase = true

[remote "origin"]
    fetch = +refs/heads/*:refs/remotes/origin/*
    url = https://github.com/quacau/test-git
[branch "master"]
    merge = refs/heads/master
    remote = origin
[user]
    email = quacau.thesphere@gmail.com 
    name = quacau
```

Here are my steps:

1. Create a new vault & install Obsidian Git
2. Clone the repo from remote (success) 
3. Make an edit and the app ask me my credential. I provide.
4. This bug happens

I'm on Android. Plugin version 2.5.1.

[I also ask this question in Stack Overflow](https://stackoverflow.com/q/74039126/3416774)

**Comment by Vinzent03** [comment]
Did you enter your GitHub password or a previously created personal access token?

**Comment by quacau** [comment]
My password. It seems that on laptop it accepts password, while on mobile it only accepts token

**Comment by Vinzent03** [comment]
I highly doubt, because GitHub has disabled that https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/

**Comment by quacau** [comment]
But why is it that in my laptop password is accepted?

**Comment by odelrio** [comment]
Do you have any instance of Obsidian running on desktop? I've found that it overrides `username` in `.obsidian/plugins/obsidian-git/data.json`.

**Comment by Vinzent03** [comment]
@odelrio That shouldn't be the cause for this issue, but should be fixed nevertheless. Thanks!

**Comment by ooker777** [comment]
So what causes the issue?

**Comment by cgc** [comment]
I had a similar issue on iOS ("Authentication failed. Please try with different credentials." on application start, though I don't think I could pull), and also had desktop overwriting `username` in `.obsidian/plugins/obsidian-git/data.json` like @odelrio says above. I think the issue was occurring after I upgraded on mobile from obsidian-git 2.0.x to 2.1.x, but hadn't explicitly reloaded or upgraded on desktop. It looks like I was able to resolve the issue by upgrading obsidian-git to 2.1.x on desktop, but I imagine simply restarting would probably have also helped.

**Comment by corderop** [comment]
@quacau It's possible that obsidian-git works on your laptop just because you have git configured there. My computer has my GitHub account configured with an SSH key, and obsidian-git is using it, even though the plugin doesn't support ssh. 

I had the same issue with my smartphone (Android). As @Vinzent03 said, it's because GitHub no longer supports password login. However, you can use a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) for this purpose. You can configure this token to provide granular access to the specific repository you use for obsidian.

**Comment by Vinzent03** [comment]
I tried to come up with the most general solution as possible, without having to install too much packages or write many config. I summarized it [here](https://github.com/denolehov/obsidian-git/wiki/Authentication). May you try it out and tell me how it's working? I can't test it on all operating systems. Especially not macOS.
