### ISSUE TITLE
[Bug]: folder not taken into account for the synchro

### ISSUE THREAD

**Issue by d4nm0** [denolehov/obsidian-git#343]
### Describe the bug

I have a folder created after the sync that is not taken into account when the push plugin on git

### Steps to reproduce

Create a folder after retrieving from git 

### Operating system

macOS

### Plugin version

latest

**Comment by A-Yaskevich** [comment]
I have the same issue. 
BTW, the folder is taken to remote repo if it is not empty. But I suppose it's not right. Event empty folders should be taken and pushed

**Comment by A-Yaskevich** [comment]
Yea, sure, you are right. From git's point of view it is a nonsense. 
But, on the other hand, let's pretend a situation when someone is designing a complex nested folder structure for future note-taking. 
A technical guy will create gitkeep or find another way to push empty folders (temp files, etc), but general person will not be able to see his complex folder structure in repo or other machine, which is pulling from repo.

**Comment by Vinzent03** [comment]
That's true, but this is still just a plugin to interact with default git. I'm not going to change the behavior of git or find tricks. As you said, you can create a .gitkeep file.

**Comment by Vinzent03** [comment]
When reopening this issue, I wanted to implement this. But after some time thinking about this, I decided yet again to not add this. I would have to go through every directory and check for no further children, but still respect `.gitignore`, because ignored directories should still not be committed. In addition, I don't think there are many people constructing a complex directory structure without using it.
