### ISSUE TITLE
Is there a way to set `--git_dir`?

### ISSUE THREAD

**Issue by zfei** [denolehov/obsidian-git#414]
I have a setup of syncing obsidian repos between Mac and Win via iCloud Drive.
Initially, I put the `.git` in the root dir of the obsidian repo, but iCloud always messes up the objects in `.git` when I switch OS.

Now I'm thinking of having a git directory for each machine locally that's not synced by iCloud, and have a host specific `--git_dir` for the plugin to pass to git binary.

Going through the current plugin setting scheme, I guess adding a `GIT_DIR` env var into the "Additional PATH env var paths" could help? Yet when I tried it out on Windows, it looks like the plugin tries to split the `:` in my disk reference, i.e. `D:\`.

Is the PATH field a right fit for my use case? If so, how do I set it on WIndows?

Thanks in advance.

**Comment by erauner12** [comment]
+1 I would like to do this as well.

Though I want to point `obsidian-git` plugin at `--git-dir=.gitContent` for the purpose of having a separation of revision history to `.md` content and obsidian vault files

**Comment by narze** [comment]
I found a workaround using plaintext `.git` file similar to this issue https://github.com/denolehov/obsidian-git/issues/55
however I cannot use `~` to direct it to my home directory so I use relative path to the vault path in iCloud

Assuming that your .git is at `~/obsidian.git`, create .git file with this content:

```
gitdir: ../../../../../obsidian.git
```

If all of your machines share the same username you can use absolute path, too

```
gitdir: /Users/yourusername/obsidian.git
```

However it would be best if this plugin supports setting git & gitdir from the plugin's option, since isomorphic-git already supported those options https://isomorphic-git.org/docs/en/dir-vs-gitdir, or at least support adding environment variables apart from `PATH` so I can set `GIT_DIR`

**Comment by Vinzent03** [comment]
You should now be able to specify a GIT_DIR via a new added setting.  Works for mobile as well.

**Comment by zfei** [comment]
Works like a charm. Thank you guys!
