### ISSUE TITLE
[Bug]: [Mobile] CheckoutConflictError: Your local changes to following files would be overwritten by checkout

### ISSUE THREAD

**Issue by ryanjrman** [denolehov/obsidian-git#493]
### Describe the bug

Happens when trying to clone an existing repo on mobile. I got it to work on mac and windows but IOS is proving troublesome. I have a fresh install of obsidian mobile so not sure why this would be happening. It happens with both config setups (.obsidian and .obsidian.mobile). Please assist if possible. Thanks!
![IMG_2066](https://user-images.githubusercontent.com/71186324/231330601-c4609acd-3cc6-4490-9a6a-e54e3433e42f.jpg)

### Steps to reproduce

Use Obsidian Git to clone an existing repo and follow the steps.

### Expected Behavior

Cloning the repo and syncing the Obsidian vault.

### Operating system

iOS

### Installation Method

None

### Plugin version

2.19.1

**Comment by wdpk** [comment]
When it asks you the question "Does your repository have an .obsidian directory?" are you hitting "Yes"? 

It then warns you if you hit yes you can then either "abort clone" or "delete all local settings, appearances, etc", which deletes the iOS .obsidian folder so that you can properly clone your repo.

alternatively, add a .gitignore file and stop the entire folder from being sync'd. add this line to the .gitignore; ".obsidian/*"

personally i have found syncing the .obsidian folder to be tricky if you like to use multiple devices semi-simultaneously. i do not sync it and use git for the vault, but not settings. additionally, i have several more plugins on desktop than mobile.

**Comment by ryanjrman** [comment]
> When it asks you the question "Does your repository have an .obsidian directory?" are you hitting "Yes"?
> 
> It then warns you if you hit yes you can then either "abort clone" or "delete all local settings, appearances, etc", which deletes the iOS .obsidian folder so that you can properly clone your repo.
> 
> alternatively, add a .gitignore file and stop the entire folder from being sync'd. add this line to the .gitignore; ".obsidian/*"
> 
> personally i have found syncing the .obsidian folder to be tricky if you like to use multiple devices semi-simultaneously. i do not sync it and use git for the vault, but not settings. additionally, i have several more plugins on desktop than mobile.

I did the .gitignore update and also hit yes and it worked! Thank you!
