### ISSUE TITLE
Doesnt work with Obsidian 0.9.10? 

### ISSUE THREAD

**Issue by ljantzen2** [denolehov/obsidian-git#7]
As with the [calendar plugin](https://github.com/liamcain/obsidian-calendar-plugin) there seems to an [issue](https://github.com/liamcain/obsidian-calendar-plugin/issues/23) with the plugin not working on version 0.9.10.  There is no gui for configuring the plugin, no commands in the command palette.

**Comment by denolehov** [comment]
Please open a console (`ctrl+shift+I`) and see if there are any errors there. Might be that plugin failed to boot.

**Comment by tiagooliveira5n** [comment]
![image](https://user-images.githubusercontent.com/39396615/98154702-ee3ebb80-1eb3-11eb-9638-da52782f02bb.png)

**Comment by denolehov** [comment]
@tiagooliveira5n I don't see the actual error on the sshot, it should be above. But please do try going to your vault directory from command line and reinitalizing repository there.

In the command line:
```
cd /path/to/your/vault
git init
```

**Comment by tiagooliveira5n** [comment]
Hello @denolehov , I reinstalled git and obsidian, however it didn't work.

I use Obsidian collaboratively with one more person. In this way, not all files in the vault are "shared", just notes from a specific folder. Probably the error is there, because my repository was configured for a folder inside the vault and not in the vault itself.

I'm going to reconfigure the repository so that it synchronizes the vault completely, because I believe that the plugin should look for the .git folder inside the vault.

But a detail, reinstalling a "clean" obsidian, unfortunately obsidian-git does not appear in the plugins part (on the bottom left). As print below:

![image](https://user-images.githubusercontent.com/39396615/98179433-8309df00-1edd-11eb-820a-14b2ba82826f.png)

**Comment by tiagooliveira5n** [comment]
Heyy @denolehov , it's working!

I reconfigured git so that the repository was the full vault.
Thanks!

![image](https://user-images.githubusercontent.com/39396615/98187476-c8370c80-1eef-11eb-99e6-2892f3524e31.png)

**Comment by ljantzen** [comment]
I am having a problem with the plugin not finding the repo.  
![image](https://user-images.githubusercontent.com/67438/98209852-ed536b80-1f3f-11eb-91ac-2485f5203974.png)
I am able to fetch and push to the repo from the command line.  The repo is private.

**Comment by ljantzen** [comment]
I just noticed that the plugin attempted to push, and the error message in the toast had the correct repo name.  So I think this may have something to do with the repo being private or the plugin not using the correct ssh  key.  The required key is located in ~/.ssh, but it is not ~/.ssh/id_rsa, it has another name.

**Comment by ljantzen** [comment]
Sorry, problem was on my end. I had a general mess of ssh keys, some of which were in my keyring and some werent. 
`ssh-add -D` to delete them all, then `ssh-add <filename>` on each file to readd them, then restarting the ssh-agent solved the issue.

**Comment by denolehov** [comment]
@ljantzen I am glad you were able to figure out the problem! Yeah, having many SSH keys might get messy :smile:

**Comment by denolehov** [comment]
@tiagooliveira5n oh, I understand your problem! Yes, plugin assumes that root of the vault is the repo itself, I honestly didn't even consider this use-case before, but now that you mention it - I think it'd be a good idea to allow specifying a custom path to git repo within obsidian vault. I will add a note to myself to investigate how this could be achieved.
